window.yingdiwang = {
    "title": "应帝王",
    "section": "内篇",
    "sentences": [
        {
            "original": "<span class=\"hz\" data-pinyin=\"niè\">啮</span><span class=\"hz\" data-pinyin=\"quē\">缺</span>问<span class=\"hz\" data-pinyin=\"yú\">于</span>王倪，四问而四不知。<span class=\"hz\" data-pinyin=\"niè\">啮</span><span class=\"hz\" data-pinyin=\"quē\">缺</span>因跃而大喜，行以告<span class=\"hz\" data-pinyin=\"pú\">蒲</span><span class=\"hz\" data-pinyin=\"yī\">衣</span>子。<span class=\"hz\" data-pinyin=\"pú\">蒲</span><span class=\"hz\" data-pinyin=\"yī\">衣</span>子曰：「而乃今知之乎？有虞氏不及泰氏。有虞氏，其犹藏仁以要人，亦得人矣，而未始出<span class=\"hz\" data-pinyin=\"yú\">于</span>非人。泰氏，其卧<span class=\"hz\" data-pinyin=\"xú\">徐</span><span class=\"hz\" data-pinyin=\"xú\">徐</span>，其觉<span class=\"hz\" data-pinyin=\"yú\">于</span><span class=\"hz\" data-pinyin=\"yú\">于</span>；一以己为马，一以己为牛；其知情信，其<span class=\"hz\" data-pinyin=\"dé\">德</span>甚真，而未始入<span class=\"hz\" data-pinyin=\"yú\">于</span>非人。」",

            "translation": "啮缺问王倪，问了四次都得到「不知道」的回答。啮缺因此高兴地跳起来，跑去告诉蒲衣子。蒲衣子说：「你现在明白了吗？有虞氏比不上泰氏。有虞氏怀着仁爱来邀结人心，也能得到人心，但未能超脱人为牵累。泰氏，睡觉时缓缓慢慢，醒来时无忧无虑；一会儿把自己当马，一会儿把自己当牛；他的智慧真实可信，德行纯真，从未陷入人为牵累。」"
        },
        {
            "original": "肩吾见狂接舆。狂接舆曰：「日中始何以语汝？」肩吾曰：「告我：君人者以己出<span class=\"hz\" data-pinyin=\"jīng\">经</span><span class=\"hz\" data-pinyin=\"shì\">式</span><span class=\"hz\" data-pinyin=\"yì\">义</span><span class=\"hz\" data-pinyin=\"dù\">度</span>，人孰敢不听而化诸！」狂接舆曰：「是<span class=\"hz\" data-pinyin=\"qī\">欺</span><span class=\"hz\" data-pinyin=\"dé\">德</span>也；其<span class=\"hz\" data-pinyin=\"yú\">于</span>治天下也，犹<span class=\"hz\" data-pinyin=\"shè\">涉</span>海<span class=\"hz\" data-pinyin=\"záo\">凿</span>河而使<span class=\"hz\" data-pinyin=\"wén\">蚊</span><span class=\"hz\" data-pinyin=\"fù\">负</span>山也。夫圣人之治也，治外乎？正而后行，<span class=\"hz\" data-pinyin=\"què\">确</span>乎能其事者而已矣。",

            "translation": "肩吾去见狂接舆。狂接舆问：「日中始告诉你什么？」肩吾说：「他告诉我：统治人民的君王凭自己制定法度，人民谁敢不听从而被感化！」狂接舆说：「这是欺德；用此法治理天下，如徒步涉海、开凿河道、让蚊子背山。圣人治理天下，是用法度治外表吗？先端正自己然后推行，只是让人确实做好各自的事罢了。」"
        },
        {
            "original": "天根游<span class=\"hz\" data-pinyin=\"yú\">于</span>殷<span class=\"hz\" data-pinyin=\"yáng\">阳</span>，至<span class=\"hz\" data-pinyin=\"liǎo\">蓼</span>水之上，适遭<span class=\"hz\" data-pinyin=\"wú\">无</span><span class=\"hz\" data-pinyin=\"míng\">名</span>人而问焉，曰：「请问为天下。」<span class=\"hz\" data-pinyin=\"wú\">无</span><span class=\"hz\" data-pinyin=\"míng\">名</span>人曰：「去！汝鄙人也，何问之不豫也！予方将与造物者为人，厌则又乘夫<span class=\"hz\" data-pinyin=\"mǎng\">莽</span><span class=\"hz\" data-pinyin=\"miǎo\">眇</span>之鸟，以出六极之外，而游<span class=\"hz\" data-pinyin=\"wú\">无</span>何有之<span class=\"hz\" data-pinyin=\"xiāng\">乡</span>，以处<span class=\"hz\" data-pinyin=\"kuàng\">圹</span><span class=\"hz\" data-pinyin=\"làng\">埌</span>之野。汝又何<span class=\"hz\" data-pinyin=\"bó\">帛</span>以治天下感予之<span class=\"hz\" data-pinyin=\"xīn\">心</span>为？」",

            "translation": "天根在殷山南面游玩，来到蓼水岸上，恰好碰到无名人便问道：「请问怎样治理天下。」无名人说：「走开！你这个鄙陋的人，为什么问这样让人不快的问题！我正要和造物者为伴，厌烦了就乘那轻虚飘渺的鸟飞出天地四方之外，遨游于虚无之地，居住于广阔旷野。你又为什么用治理天下的话来触动我的心？」"
        },
        {
            "original": "<span class=\"hz\" data-pinyin=\"yáng\">阳</span>子<span class=\"hz\" data-pinyin=\"jū\">居</span>见老聃，曰：「有人<span class=\"hz\" data-pinyin=\"yú\">于</span>此，<span class=\"hz\" data-pinyin=\"xiàng\">向</span><span class=\"hz\" data-pinyin=\"jí\">疾</span><span class=\"hz\" data-pinyin=\"qiáng\">强</span><span class=\"hz\" data-pinyin=\"liáng\">梁</span>，物<span class=\"hz\" data-pinyin=\"chè\">彻</span><span class=\"hz\" data-pinyin=\"shū\">疏</span>明，学道不倦。如是者，可比明王乎？」老聃曰：「是<span class=\"hz\" data-pinyin=\"yú\">于</span>圣人也，<span class=\"hz\" data-pinyin=\"xū\">胥</span><span class=\"hz\" data-pinyin=\"yì\">易</span><span class=\"hz\" data-pinyin=\"jì\">技</span><span class=\"hz\" data-pinyin=\"xì\">系</span>，劳形<span class=\"hz\" data-pinyin=\"chù\">怵</span><span class=\"hz\" data-pinyin=\"xīn\">心</span>者也。且也<span class=\"hz\" data-pinyin=\"hǔ\">虎</span><span class=\"hz\" data-pinyin=\"bào\">豹</span>之<span class=\"hz\" data-pinyin=\"wén\">文</span>来<span class=\"hz\" data-pinyin=\"tián\">田</span>，<span class=\"hz\" data-pinyin=\"yuán\">猿</span><span class=\"hz\" data-pinyin=\"jū\">狙</span>之<span class=\"hz\" data-pinyin=\"biàn\">便</span>执斄之狗来<span class=\"hz\" data-pinyin=\"jí\">藉</span>。如是者，可比明王乎？」",

            "translation": "阳子居去见老子，说：「有这样一个人，敏捷果敢，洞察事物清明通透，学道孜孜不倦。像这样的人，可比得上明王吗？」老子说：「这样的人在圣人看来，只是像胥吏那样变换技艺、被技能束缚，劳累形体、惊扰心神的人。况且虎豹因皮毛有花纹而招来猎捕，猿猴因敏捷、猎狗因能捉犛牛而招来束缚。像这样的人，可比得上明王吗？」"
        },
        {
            "original": "<span class=\"hz\" data-pinyin=\"yáng\">阳</span>子<span class=\"hz\" data-pinyin=\"jū\">居</span><span class=\"hz\" data-pinyin=\"cù\">蹴</span>然曰：「敢问明王之治。」老聃曰：「明王之治：功盖天下而似不自己，化<span class=\"hz\" data-pinyin=\"dài\">贷</span>万物而民弗<span class=\"hz\" data-pinyin=\"shì\">恃</span>；有莫举<span class=\"hz\" data-pinyin=\"míng\">名</span>，使物自喜；立乎不测，而游<span class=\"hz\" data-pinyin=\"yú\">于</span><span class=\"hz\" data-pinyin=\"wú\">无</span>有者也。」",

            "translation": "阳子居恭敬地问：「请问明王是怎样治理的。」老子说：「明王的治理：功业盖过天下却好像不是出自自己，教化施及万物而人民不依赖他；有功德却无可称名，使万物各得其所而自得其乐；立足于不可测度之境，而遨游于虚无的境地。」"
        },
        {
            "original": "郑有神<span class=\"hz\" data-pinyin=\"wū\">巫</span>曰季<span class=\"hz\" data-pinyin=\"xián\">咸</span>，知人之死生存亡、祸福寿夭，<span class=\"hz\" data-pinyin=\"jī\">期</span>以岁月<span class=\"hz\" data-pinyin=\"xún\">旬</span>日，<span class=\"hz\" data-pinyin=\"ruò\">若</span>神。郑人见之，皆弃而走。列子见之而<span class=\"hz\" data-pinyin=\"xīn\">心</span><span class=\"hz\" data-pinyin=\"zuì\">醉</span>，归，以告<span class=\"hz\" data-pinyin=\"hú\">壶</span>子，曰：「始吾以夫子之道为至矣，则又有至焉者矣。」",

            "translation": "郑国有个神巫叫季咸，能知道人的死生、存亡、祸福、寿夭，预言的年月旬日准确如神。郑国人见到他，都惊慌逃走。列子见到他而心醉神往，回去告诉壶子说：「起初我以为先生的道最高了，却又有更高的了。」"
        },
        {
            "original": "明日，列子与之见<span class=\"hz\" data-pinyin=\"hú\">壶</span>子。出而谓列子曰：「嘻！子之先生死矣！弗活矣！不以<span class=\"hz\" data-pinyin=\"xún\">旬</span>数矣！吾见怪焉，见湿灰焉。」列子入，泣涕沾襟以告<span class=\"hz\" data-pinyin=\"hú\">壶</span>子。<span class=\"hz\" data-pinyin=\"hú\">壶</span>子曰：「<span class=\"hz\" data-pinyin=\"xiāng\">乡</span>吾示之以地<span class=\"hz\" data-pinyin=\"wén\">文</span>，萌乎不震不正。是殆见吾<span class=\"hz\" data-pinyin=\"dù\">杜</span><span class=\"hz\" data-pinyin=\"dé\">德</span><span class=\"hz\" data-pinyin=\"jī\">机</span>也。尝又与来。」",

            "translation": "第二天，列子带季咸来见壶子。季咸出来后对列子说：「唉！你的先生要死了！活不成了！过不了十天了！我看见怪状，看见湿灰一样的死气。」列子进去，哭得眼泪沾湿衣襟，告诉壶子。壶子说：「刚才我显示给他看的是地象，萌动而不震不正。这大概是看见我闭塞了生机。再带他来看看。」"
        },
        {
            "original": "明日，又与之见<span class=\"hz\" data-pinyin=\"hú\">壶</span>子。出而谓列子曰：「幸矣，子之先生遇我也！有<span class=\"hz\" data-pinyin=\"chōu\">瘳</span>矣，全然有生矣！吾见其<span class=\"hz\" data-pinyin=\"dù\">杜</span><span class=\"hz\" data-pinyin=\"quán\">权</span>矣。」列子入，以告<span class=\"hz\" data-pinyin=\"hú\">壶</span>子。<span class=\"hz\" data-pinyin=\"hú\">壶</span>子曰：「<span class=\"hz\" data-pinyin=\"xiāng\">乡</span>吾示之以天壤，<span class=\"hz\" data-pinyin=\"míng\">名</span>实不入，而<span class=\"hz\" data-pinyin=\"jī\">机</span>发<span class=\"hz\" data-pinyin=\"yú\">于</span><span class=\"hz\" data-pinyin=\"zhǒng\">踵</span>。是殆见吾善者<span class=\"hz\" data-pinyin=\"jī\">机</span>也。尝又与来。」",

            "translation": "第二天，又带季咸来见壶子。季咸出来后对列子说：「幸运啊，你的先生遇到我！有救了，完全有生机了！我看见他闭塞的生机开始活动了。」列子进去，告诉壶子。壶子说：「刚才我显示给他看的是天壤之象，名实不入于心，而生机发自脚跟。这大概是看见我善的生机。再带他来看看。」"
        },
        {
            "original": "明日，又与之见<span class=\"hz\" data-pinyin=\"hú\">壶</span>子。立未定，自失而走。<span class=\"hz\" data-pinyin=\"hú\">壶</span>子曰：「追之！」列子追之不及。反，以报<span class=\"hz\" data-pinyin=\"hú\">壶</span>子曰：「已灭矣，已失矣，吾弗及已。」<span class=\"hz\" data-pinyin=\"hú\">壶</span>子曰：「<span class=\"hz\" data-pinyin=\"xiāng\">乡</span>吾示之以未始出吾宗。吾与之虚而委蛇，不知其谁何，因以为<span class=\"hz\" data-pinyin=\"tì\">弟</span><span class=\"hz\" data-pinyin=\"mǐ\">靡</span>，因以为<span class=\"hz\" data-pinyin=\"bō\">波</span><span class=\"hz\" data-pinyin=\"liú\">流</span>，故逃也。」",

            "translation": "第二天，又带季咸来见壶子。季咸还没站稳，就惊慌逃走。壶子说：「追他！」列子追不上。回来报告壶子说：「已经不见了，已经失去了，我追不上了。」壶子说：「刚才我显示给他看的是还没有出示我的根本大道。我与他虚己而随顺，他不知道我是什么，因而以为我随波逐流，所以逃走了。」"
        },
        {
            "original": "<span class=\"hz\" data-pinyin=\"wú\">无</span>为<span class=\"hz\" data-pinyin=\"míng\">名</span>尸，<span class=\"hz\" data-pinyin=\"wú\">无</span>为谋府；<span class=\"hz\" data-pinyin=\"wú\">无</span>为事任，<span class=\"hz\" data-pinyin=\"wú\">无</span>为知主。体尽<span class=\"hz\" data-pinyin=\"wú\">无</span>穷，而游<span class=\"hz\" data-pinyin=\"wú\">无</span><span class=\"hz\" data-pinyin=\"zhèn\">朕</span>；尽其所受乎天，而<span class=\"hz\" data-pinyin=\"wú\">无</span>见得，亦虚而已。至人之用<span class=\"hz\" data-pinyin=\"xīn\">心</span><span class=\"hz\" data-pinyin=\"ruò\">若</span>镜，不将不迎，应而不藏，故能胜物而不伤。",

            "translation": "不要成为名声的尸主，不要成为谋虑的府库；不要成为事务的任使，不要成为智慧的主宰。体悟穷尽无穷的大道，而遨游于无迹之境；尽享所受于自然的本性，而不自以为有所得，这也只是虚己罢了。至人的用心像镜子一样，不送不迎，应接而不隐藏，所以能胜过外物而不被伤害。"
        },
        {
            "original": "南海之帝为<span class=\"hz\" data-pinyin=\"shū\">倏</span>，北海之帝为<span class=\"hz\" data-pinyin=\"hū\">忽</span>，中央之帝为<span class=\"hz\" data-pinyin=\"hún\">浑</span><span class=\"hz\" data-pinyin=\"dùn\">沌</span>。<span class=\"hz\" data-pinyin=\"shū\">倏</span>与<span class=\"hz\" data-pinyin=\"hū\">忽</span>时相与遇<span class=\"hz\" data-pinyin=\"yú\">于</span><span class=\"hz\" data-pinyin=\"hún\">浑</span><span class=\"hz\" data-pinyin=\"dùn\">沌</span>之地，<span class=\"hz\" data-pinyin=\"hún\">浑</span><span class=\"hz\" data-pinyin=\"dùn\">沌</span>待之甚善。<span class=\"hz\" data-pinyin=\"shū\">倏</span>与<span class=\"hz\" data-pinyin=\"hū\">忽</span>谋报<span class=\"hz\" data-pinyin=\"hún\">浑</span><span class=\"hz\" data-pinyin=\"dùn\">沌</span>之<span class=\"hz\" data-pinyin=\"dé\">德</span>，曰：「人皆有七<span class=\"hz\" data-pinyin=\"qiào\">窍</span>以视听食息，此独<span class=\"hz\" data-pinyin=\"wú\">无</span>有，尝试<span class=\"hz\" data-pinyin=\"záo\">凿</span>之。」日<span class=\"hz\" data-pinyin=\"záo\">凿</span>一<span class=\"hz\" data-pinyin=\"qiào\">窍</span>，七日而<span class=\"hz\" data-pinyin=\"hún\">浑</span><span class=\"hz\" data-pinyin=\"dùn\">沌</span>死。",

            "translation": "南海的帝王叫倏，北海的帝王叫忽，中央的帝王叫浑沌。倏和忽时常在浑沌的地方相遇，浑沌待他们很好。倏和忽商量报答浑沌的恩德，说：「人都有七窍用来看、听、吃、呼吸，唯独浑沌没有，试着给他开凿出来。」每天开凿一窍，七天之后浑沌死了。"
        }
    ],
    "interpretation": "<h3>内容梗概</h3><p>《应帝王》是《庄子》内篇的最后一篇，主要论述帝王治理天下的原则。篇名「应帝王」意为「帝王应该怎样治理天下」。庄子认为，真正的帝王不应以仁义礼法束缚人民，而应顺应自然、无为而治。全篇以啮缺问王倪引出泰氏「其卧徐徐，其觉于于」的无为境界；以狂接舆批评「以己出经式义度」的欺德之治；以壶子示相揭示得道者的不可测度；最后以「浑沌凿七窍」的寓言作结——人为干预会破坏自然，无为而治方能天下太平。</p><h3>全文结构</h3><p><strong>第一层（有虞氏与泰氏）</strong>：啮缺问王倪，四问四不知。蒲衣子借此对比有虞氏与泰氏：有虞氏「藏仁以要人」，虽能得人，但未超脱人为；泰氏「其卧徐徐，其觉于于」，随顺自然，从未陷入人为牵累。</p><p><strong>第二层（圣人之治）</strong>：狂接舆批评「以己出经式义度」的治理方式，认为这是「欺德」。圣人之治应是「正而后行，确乎能其事者」——先端正自己，然后让人做好各自的事。明王之治「功盖天下而似不自己」，化育万物而不使人依赖。</p><p><strong>第三层（壶子示相）</strong>：列子引神巫季咸为壶子看相，壶子先后显示地文、天壤、太冲莫胜、未始出吾宗四种境界。季咸从断言必死、说有生机，到无法看相，最后惊慌逃走。说明真正得道者深不可测，不露迹象。</p><p><strong>第四层（浑沌之喻）</strong>：南海之帝倏和北海之帝忽为了报答中央之帝浑沌的款待，每天为浑沌开凿一窍，结果七窍开而浑沌死。这是内七篇的压轴之笔——人为的干预会破坏自然的本性，治国也应顺其自然。</p><h3>总结</h3><p>《应帝王》以内七篇最简洁的篇幅，传达了最深刻的信息：最好的治理是不治理。泰氏「一以己为马，一以己为牛」的随顺，壶子「虚而委蛇」的不可测度，浑沌「七窍未开」的浑全，都指向同一个真理——自然的状态是最完美的，任何人为的雕琢都是破坏。这对当代管理者、教育者、父母都有深刻启示：放下控制欲，顺应自然规律，让万物自化，才是真正的智慧。</p>",
    "insight": "<h3>哲学本源</h3><p>《应帝王》的哲学根基是道家的「无为而治」。庄子批判了儒家式的有为政治——以仁义礼法约束人民，以刑赏驾驭百姓。在庄子看来，这种治理是「欺德」——欺骗了人的自然德性。真正的圣人之治是「正而后行，确乎能其事者」——统治者先端正自己，然后让人民自然做好自己的事。</p><p>「明王之治：功盖天下而似不自己」——最好的统治者，人民感受不到他的存在。这与老子「太上，下知有之」的思想一脉相承。统治者不居功、不控制、不强求，只是顺应自然规律，让万物各得其所。</p><p>「浑沌凿七窍」的寓言是庄子政治哲学的巅峰表达：浑沌代表自然的、未被分化的整全状态；七窍代表人为的、分析性的认知方式。为浑沌开七窍，如同用理性切割自然，结果是整全性的死亡。这隐喻着：文明的发展、制度的建立、知识的积累，如果违背了自然本性，就会带来灾难。</p><h3>现代生活应用</h3><p><strong>一、管理智慧：从控制到赋能</strong></p><p>「明王之治：功盖天下而似不自己」——最好的领导，下属感受不到他的控制。现代管理学从「命令-控制」模式转向「赋能-自主」模式，与庄子的无为而治异曲同工。优秀的管理者不是事事亲力亲为，而是建立制度、营造文化，让团队自然运转。就像园丁不替花生长，只是除草浇水。</p><p><strong>二、教育启示：不要凿浑沌之窍</strong></p><p>「浑沌凿七窍」的寓言对教育有深刻警示。现代教育往往急于给孩子「开窍」——早教、培训班、才艺课，恨不得把孩子的每一分钟都填满。但庄子提醒我们：每个孩子都是浑沌，有其自然的成长节奏。过早的、过度的干预，可能会「凿死浑沌」——扼杀孩子的天性、创造力和内在动力。尊重孩子的自然发展，比灌输知识更重要。</p><p><strong>三、人际关系：用心若镜</strong></p><p>「至人之用心若镜，不将不迎，应而不藏」——至人的心像镜子，如实反映而不执着。在人际关系中，这意味着：不预设期待（不将），不刻意讨好（不迎），真诚回应（应），不隐藏算计（不藏）。这种「镜心」的态度，能让我们在复杂的人际网络中保持清醒，不被情绪和他人的期待所左右。</p><p><strong>四、个人修养：无为名尸，无为谋府</strong><p>「无为名尸，无为谋府」——不要成为名声的奴隶，不要成为谋虑的仓库。在功利的社会中，人们追逐名声、精于算计，却活得很累。庄子提醒我们：放下对名声的执着，停止过度的谋划，回归内心的虚静。当一个人不再为外界的评价而活，不再为未来的焦虑而谋划，才能真正获得自由。</p><p><strong>五、创新思维：不可测度的价值</strong></p><p>壶子示相的故事说明：真正的高深境界是不可测度的。在商业竞争中，「不可测度」就是最大的护城河。当对手无法预判你的下一步，你就掌握了主动权。这提醒我们：不要过早暴露自己的底牌，保持适度的神秘感，是生存和竞争的智慧。</p>",
    "example": "<p><strong>汉文帝「无为而治」——文景之治的典范</strong></p><p>汉文帝刘恒是历史上著名的无为而治的君主。他即位后，废除苛法，轻徭薄赋，与民休息。《史记》记载：「文帝即位二十三年，宫室苑囿狗马服御无所增益。」他不像秦始皇那样大兴土木，不像汉武帝那样穷兵黩武，而是「顺物自然」，让百姓自主生息。正是这几十年的无为而治，开创了「文景之治」，为汉武帝的盛世奠定了基础。（出自《史记·孝文本纪》）</p><p><strong>诸葛亮「治蜀」——有为与无为的平衡</strong></p><p>诸葛亮治蜀，一方面「鞠躬尽瘁，死而后已」，事必躬亲；另一方面又深知「治外乎？正而后行」的道理。他制定《蜀科》，依法治国，但「刑政虽峻而无怨者，以其用心平而劝戒明也」。诸葛亮在《诫子书》中说：「非淡泊无以明志，非宁静无以致远。」这种淡泊宁静的心态，正是「用心若镜」的体现。（出自《三国志·蜀书·诸葛亮传》）</p><p><strong>郑板桥「难得糊涂」——浑沌智慧的民间传承</strong></p><p>清代郑板桥题「难得糊涂」四字，并跋曰：「聪明难，糊涂尤难，由聪明而转入糊涂更难。放一着，退一步，当下心安，非图后来福报也。」这正是《应帝王》「浑沌凿七窍」寓言的民间演绎——过于精明、过于计较，反而会失去生活的本真。保持一点「糊涂」，不被世俗的「七窍」所束缚，才能保全浑沌般的自然本性。（出自《郑板桥集》）</p>"
};
